#############################################################################
# Makefile for building: iot2
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  iot2.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt5/bin/qmake -o Makefile iot2.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Ilib/mqtt-inc -Ilib/dropbox -Ilib/QtTelegramBot -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -isystem /usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = iot21.0.0
DISTDIR = /home/android/iot/iot2/.tmp/iot21.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lqmqtt -lwiringPi -lQtDropbox2 -lopencv_core -lopencv_imgproc -lQt5Network -lQt5SerialPort -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = lib/QtTelegramBot/qttelegrambot.cpp \
		lib/QtTelegramBot/networking.cpp \
		lib/QtTelegramBot/types/message.cpp \
		lib/QtTelegramBot/types/update.cpp \
		lib/QtTelegramBot/types/chat.cpp \
		lib/QtTelegramBot/types/user.cpp \
		lib/QtTelegramBot/types/document.cpp \
		lib/QtTelegramBot/types/photosize.cpp \
		lib/QtTelegramBot/types/audio.cpp \
		lib/QtTelegramBot/types/sticker.cpp \
		lib/QtTelegramBot/types/video.cpp \
		lib/QtTelegramBot/types/voice.cpp \
		lib/QtTelegramBot/types/contact.cpp \
		lib/QtTelegramBot/types/location.cpp \
		main.cpp \
		ssd1306/ssd1306.c \
		ssd1306/ubuntuMono_8pt.c \
		ssd1306/ubuntuMono_16pt.c \
		ssd1306/ubuntuMono_24pt.c \
		ssd1306/ubuntuMono_48pt.c \
		settings.cpp \
		uartdevice.cpp \
		modem.cpp \
		dht.cpp \
		cameradev.cpp \
		camerathread.cpp \
		pininaction.cpp \
		pinoutaction.cpp \
		display.cpp \
		body.cpp \
		bme280.cpp \
		imageconverter.cpp \
		filesender.cpp \
		motiondetector.cpp \
		webstream.cpp moc_qttelegrambot.cpp \
		moc_networking.cpp \
		moc_uartdevice.cpp \
		moc_modem.cpp \
		moc_dht.cpp \
		moc_camerathread.cpp \
		moc_pininaction.cpp \
		moc_pinoutaction.cpp \
		moc_display.cpp \
		moc_body.cpp \
		moc_filesender.cpp \
		moc_motiondetector.cpp \
		moc_webstream.cpp
OBJECTS       = qttelegrambot.o \
		networking.o \
		message.o \
		update.o \
		chat.o \
		user.o \
		document.o \
		photosize.o \
		audio.o \
		sticker.o \
		video.o \
		voice.o \
		contact.o \
		location.o \
		main.o \
		ssd1306.o \
		ubuntuMono_8pt.o \
		ubuntuMono_16pt.o \
		ubuntuMono_24pt.o \
		ubuntuMono_48pt.o \
		settings.o \
		uartdevice.o \
		modem.o \
		dht.o \
		cameradev.o \
		camerathread.o \
		pininaction.o \
		pinoutaction.o \
		display.o \
		body.o \
		bme280.o \
		imageconverter.o \
		filesender.o \
		motiondetector.o \
		webstream.o \
		moc_qttelegrambot.o \
		moc_networking.o \
		moc_uartdevice.o \
		moc_modem.o \
		moc_dht.o \
		moc_camerathread.o \
		moc_pininaction.o \
		moc_pinoutaction.o \
		moc_display.o \
		moc_body.o \
		moc_filesender.o \
		moc_motiondetector.o \
		moc_webstream.o
DIST          = /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmqtt.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmqtt_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		lib/QtTelegramBot/QtTelegramBot.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		iot2.pro lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		images.h \
		ssd1306/font.h \
		ssd1306/ssd1306.h \
		ssd1306/ubuntuMono_8pt.h \
		ssd1306/ubuntuMono_16pt.h \
		ssd1306/ubuntuMono_24pt.h \
		ssd1306/ubuntuMono_48pt.h \
		defines.h \
		settings.h \
		uartdevice.h \
		modem.h \
		dht.h \
		cameradev.h \
		camerathread.h \
		pininaction.h \
		pinoutaction.h \
		display.h \
		body.h \
		bme280.h \
		imageconverter.h \
		filesender.h \
		motiondetector.h \
		webstream.h lib/QtTelegramBot/qttelegrambot.cpp \
		lib/QtTelegramBot/networking.cpp \
		lib/QtTelegramBot/types/message.cpp \
		lib/QtTelegramBot/types/update.cpp \
		lib/QtTelegramBot/types/chat.cpp \
		lib/QtTelegramBot/types/user.cpp \
		lib/QtTelegramBot/types/document.cpp \
		lib/QtTelegramBot/types/photosize.cpp \
		lib/QtTelegramBot/types/audio.cpp \
		lib/QtTelegramBot/types/sticker.cpp \
		lib/QtTelegramBot/types/video.cpp \
		lib/QtTelegramBot/types/voice.cpp \
		lib/QtTelegramBot/types/contact.cpp \
		lib/QtTelegramBot/types/location.cpp \
		main.cpp \
		ssd1306/ssd1306.c \
		ssd1306/ubuntuMono_8pt.c \
		ssd1306/ubuntuMono_16pt.c \
		ssd1306/ubuntuMono_24pt.c \
		ssd1306/ubuntuMono_48pt.c \
		settings.cpp \
		uartdevice.cpp \
		modem.cpp \
		dht.cpp \
		cameradev.cpp \
		camerathread.cpp \
		pininaction.cpp \
		pinoutaction.cpp \
		display.cpp \
		body.cpp \
		bme280.cpp \
		imageconverter.cpp \
		filesender.cpp \
		motiondetector.cpp \
		webstream.cpp
QMAKE_TARGET  = iot2
DESTDIR       = 
TARGET        = iot2


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: iot2.pro /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmqtt.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmqtt_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		lib/QtTelegramBot/QtTelegramBot.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		iot2.pro \
		/usr/lib/arm-linux-gnueabihf/libqmqtt.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Network.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5SerialPort.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5PrintSupport.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Core.prl
	$(QMAKE) -o Makefile iot2.pro
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmqtt.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_qmqtt_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf:
lib/QtTelegramBot/QtTelegramBot.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf:
iot2.pro:
/usr/lib/arm-linux-gnueabihf/libqmqtt.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Network.prl:
/usr/lib/arm-linux-gnueabihf/libQt5SerialPort.prl:
/usr/lib/arm-linux-gnueabihf/libQt5PrintSupport.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile iot2.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents lib/QtTelegramBot/qttelegrambot.h lib/QtTelegramBot/networking.h lib/QtTelegramBot/types/message.h lib/QtTelegramBot/types/update.h lib/QtTelegramBot/types/chat.h lib/QtTelegramBot/types/user.h lib/QtTelegramBot/types/file.h lib/QtTelegramBot/types/document.h lib/QtTelegramBot/types/photosize.h lib/QtTelegramBot/types/audio.h lib/QtTelegramBot/types/sticker.h lib/QtTelegramBot/types/video.h lib/QtTelegramBot/types/voice.h lib/QtTelegramBot/types/contact.h lib/QtTelegramBot/types/location.h lib/QtTelegramBot/types/reply/genericreply.h lib/QtTelegramBot/types/reply/replykeyboardmarkup.h lib/QtTelegramBot/types/reply/replykeyboardhide.h lib/QtTelegramBot/types/reply/forcereply.h images.h ssd1306/font.h ssd1306/ssd1306.h ssd1306/ubuntuMono_8pt.h ssd1306/ubuntuMono_16pt.h ssd1306/ubuntuMono_24pt.h ssd1306/ubuntuMono_48pt.h defines.h settings.h uartdevice.h modem.h dht.h cameradev.h camerathread.h pininaction.h pinoutaction.h display.h body.h bme280.h imageconverter.h filesender.h motiondetector.h webstream.h $(DISTDIR)/
	$(COPY_FILE) --parents lib/QtTelegramBot/qttelegrambot.cpp lib/QtTelegramBot/networking.cpp lib/QtTelegramBot/types/message.cpp lib/QtTelegramBot/types/update.cpp lib/QtTelegramBot/types/chat.cpp lib/QtTelegramBot/types/user.cpp lib/QtTelegramBot/types/document.cpp lib/QtTelegramBot/types/photosize.cpp lib/QtTelegramBot/types/audio.cpp lib/QtTelegramBot/types/sticker.cpp lib/QtTelegramBot/types/video.cpp lib/QtTelegramBot/types/voice.cpp lib/QtTelegramBot/types/contact.cpp lib/QtTelegramBot/types/location.cpp main.cpp ssd1306/ssd1306.c ssd1306/ubuntuMono_8pt.c ssd1306/ubuntuMono_16pt.c ssd1306/ubuntuMono_24pt.c ssd1306/ubuntuMono_48pt.c settings.cpp uartdevice.cpp modem.cpp dht.cpp cameradev.cpp camerathread.cpp pininaction.cpp pinoutaction.cpp display.cpp body.cpp bme280.cpp imageconverter.cpp filesender.cpp motiondetector.cpp webstream.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_qttelegrambot.cpp moc_networking.cpp moc_uartdevice.cpp moc_modem.cpp moc_dht.cpp moc_camerathread.cpp moc_pininaction.cpp moc_pinoutaction.cpp moc_display.cpp moc_body.cpp moc_filesender.cpp moc_motiondetector.cpp moc_webstream.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qttelegrambot.cpp moc_networking.cpp moc_uartdevice.cpp moc_modem.cpp moc_dht.cpp moc_camerathread.cpp moc_pininaction.cpp moc_pinoutaction.cpp moc_display.cpp moc_body.cpp moc_filesender.cpp moc_motiondetector.cpp moc_webstream.cpp
moc_qttelegrambot.cpp: lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		lib/QtTelegramBot/qttelegrambot.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include lib/QtTelegramBot/qttelegrambot.h -o moc_qttelegrambot.cpp

moc_networking.cpp: lib/QtTelegramBot/networking.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include lib/QtTelegramBot/networking.h -o moc_networking.cpp

moc_uartdevice.cpp: uartdevice.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include uartdevice.h -o moc_uartdevice.cpp

moc_modem.cpp: uartdevice.h \
		modem.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include modem.h -o moc_modem.cpp

moc_dht.cpp: dht.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include dht.h -o moc_dht.cpp

moc_camerathread.cpp: cameradev.h \
		camerathread.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include camerathread.h -o moc_camerathread.cpp

moc_pininaction.cpp: pininaction.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include pininaction.h -o moc_pininaction.cpp

moc_pinoutaction.cpp: pinoutaction.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include pinoutaction.h -o moc_pinoutaction.cpp

moc_display.cpp: ssd1306/ssd1306.h \
		ssd1306/font.h \
		ssd1306/ubuntuMono_8pt.h \
		ssd1306/ubuntuMono_16pt.h \
		ssd1306/ubuntuMono_24pt.h \
		ssd1306/ubuntuMono_48pt.h \
		images.h \
		display.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include display.h -o moc_display.cpp

moc_body.cpp: lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		settings.h \
		pinoutaction.h \
		dht.h \
		cameradev.h \
		camerathread.h \
		images.h \
		defines.h \
		display.h \
		ssd1306/ssd1306.h \
		ssd1306/font.h \
		ssd1306/ubuntuMono_8pt.h \
		ssd1306/ubuntuMono_16pt.h \
		ssd1306/ubuntuMono_24pt.h \
		ssd1306/ubuntuMono_48pt.h \
		bme280.h \
		filesender.h \
		lib/dropbox/qdropbox2.h \
		lib/dropbox/qdropbox2common.h \
		lib/dropbox/qdropbox2global.h \
		lib/dropbox/qdropbox2account.h \
		lib/dropbox/qdropbox2entityinfo.h \
		lib/dropbox/qdropbox2file.h \
		lib/dropbox/qdropbox2entity.h \
		imageconverter.h \
		motiondetector.h \
		webstream.h \
		body.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include body.h -o moc_body.cpp

moc_filesender.cpp: lib/dropbox/qdropbox2.h \
		lib/dropbox/qdropbox2common.h \
		lib/dropbox/qdropbox2global.h \
		lib/dropbox/qdropbox2account.h \
		lib/dropbox/qdropbox2entityinfo.h \
		lib/dropbox/qdropbox2file.h \
		lib/dropbox/qdropbox2entity.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		defines.h \
		filesender.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include filesender.h -o moc_filesender.cpp

moc_motiondetector.cpp: motiondetector.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include motiondetector.h -o moc_motiondetector.cpp

moc_webstream.cpp: camerathread.h \
		cameradev.h \
		webstream.h \
		/usr/lib/arm-linux-gnueabihf/qt5/bin/moc
	/usr/lib/arm-linux-gnueabihf/qt5/bin/moc $(DEFINES) -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/android/iot/iot2 -I/home/android/iot/iot2/lib/mqtt-inc -I/home/android/iot/iot2/lib/dropbox -I/home/android/iot/iot2/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtSerialPort -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/arm-linux-gnueabihf/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/arm-linux-gnueabihf/6/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include webstream.h -o moc_webstream.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

qttelegrambot.o: lib/QtTelegramBot/qttelegrambot.cpp lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qttelegrambot.o lib/QtTelegramBot/qttelegrambot.cpp

networking.o: lib/QtTelegramBot/networking.cpp lib/QtTelegramBot/networking.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networking.o lib/QtTelegramBot/networking.cpp

message.o: lib/QtTelegramBot/types/message.cpp lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o message.o lib/QtTelegramBot/types/message.cpp

update.o: lib/QtTelegramBot/types/update.cpp lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o update.o lib/QtTelegramBot/types/update.cpp

chat.o: lib/QtTelegramBot/types/chat.cpp lib/QtTelegramBot/types/chat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chat.o lib/QtTelegramBot/types/chat.cpp

user.o: lib/QtTelegramBot/types/user.cpp lib/QtTelegramBot/types/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o lib/QtTelegramBot/types/user.cpp

document.o: lib/QtTelegramBot/types/document.cpp lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o document.o lib/QtTelegramBot/types/document.cpp

photosize.o: lib/QtTelegramBot/types/photosize.cpp lib/QtTelegramBot/types/photosize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o photosize.o lib/QtTelegramBot/types/photosize.cpp

audio.o: lib/QtTelegramBot/types/audio.cpp lib/QtTelegramBot/types/audio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audio.o lib/QtTelegramBot/types/audio.cpp

sticker.o: lib/QtTelegramBot/types/sticker.cpp lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/photosize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sticker.o lib/QtTelegramBot/types/sticker.cpp

video.o: lib/QtTelegramBot/types/video.cpp lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/photosize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video.o lib/QtTelegramBot/types/video.cpp

voice.o: lib/QtTelegramBot/types/voice.cpp lib/QtTelegramBot/types/voice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o voice.o lib/QtTelegramBot/types/voice.cpp

contact.o: lib/QtTelegramBot/types/contact.cpp lib/QtTelegramBot/types/contact.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contact.o lib/QtTelegramBot/types/contact.cpp

location.o: lib/QtTelegramBot/types/location.cpp lib/QtTelegramBot/types/location.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o location.o lib/QtTelegramBot/types/location.cpp

main.o: main.cpp display.h \
		ssd1306/ssd1306.h \
		ssd1306/font.h \
		ssd1306/ubuntuMono_8pt.h \
		ssd1306/ubuntuMono_16pt.h \
		ssd1306/ubuntuMono_24pt.h \
		ssd1306/ubuntuMono_48pt.h \
		images.h \
		body.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		settings.h \
		pinoutaction.h \
		dht.h \
		cameradev.h \
		camerathread.h \
		defines.h \
		bme280.h \
		filesender.h \
		lib/dropbox/qdropbox2.h \
		lib/dropbox/qdropbox2common.h \
		lib/dropbox/qdropbox2global.h \
		lib/dropbox/qdropbox2account.h \
		lib/dropbox/qdropbox2entityinfo.h \
		lib/dropbox/qdropbox2file.h \
		lib/dropbox/qdropbox2entity.h \
		imageconverter.h \
		motiondetector.h \
		webstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ssd1306.o: ssd1306/ssd1306.c ssd1306/ssd1306.h \
		ssd1306/font.h \
		ssd1306/ubuntuMono_8pt.h \
		ssd1306/ubuntuMono_16pt.h \
		ssd1306/ubuntuMono_24pt.h \
		ssd1306/ubuntuMono_48pt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ssd1306.o ssd1306/ssd1306.c

ubuntuMono_8pt.o: ssd1306/ubuntuMono_8pt.c ssd1306/font.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ubuntuMono_8pt.o ssd1306/ubuntuMono_8pt.c

ubuntuMono_16pt.o: ssd1306/ubuntuMono_16pt.c ssd1306/font.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ubuntuMono_16pt.o ssd1306/ubuntuMono_16pt.c

ubuntuMono_24pt.o: ssd1306/ubuntuMono_24pt.c ssd1306/font.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ubuntuMono_24pt.o ssd1306/ubuntuMono_24pt.c

ubuntuMono_48pt.o: ssd1306/ubuntuMono_48pt.c ssd1306/font.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ubuntuMono_48pt.o ssd1306/ubuntuMono_48pt.c

settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

uartdevice.o: uartdevice.cpp uartdevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uartdevice.o uartdevice.cpp

modem.o: modem.cpp modem.h \
		uartdevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modem.o modem.cpp

dht.o: dht.cpp dht.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dht.o dht.cpp

cameradev.o: cameradev.cpp cameradev.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cameradev.o cameradev.cpp

camerathread.o: camerathread.cpp camerathread.h \
		cameradev.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camerathread.o camerathread.cpp

pininaction.o: pininaction.cpp pininaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pininaction.o pininaction.cpp

pinoutaction.o: pinoutaction.cpp pinoutaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pinoutaction.o pinoutaction.cpp

display.o: display.cpp display.h \
		ssd1306/ssd1306.h \
		ssd1306/font.h \
		ssd1306/ubuntuMono_8pt.h \
		ssd1306/ubuntuMono_16pt.h \
		ssd1306/ubuntuMono_24pt.h \
		ssd1306/ubuntuMono_48pt.h \
		images.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o display.o display.cpp

body.o: body.cpp body.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		settings.h \
		pinoutaction.h \
		dht.h \
		cameradev.h \
		camerathread.h \
		images.h \
		defines.h \
		display.h \
		ssd1306/ssd1306.h \
		ssd1306/font.h \
		ssd1306/ubuntuMono_8pt.h \
		ssd1306/ubuntuMono_16pt.h \
		ssd1306/ubuntuMono_24pt.h \
		ssd1306/ubuntuMono_48pt.h \
		bme280.h \
		filesender.h \
		lib/dropbox/qdropbox2.h \
		lib/dropbox/qdropbox2common.h \
		lib/dropbox/qdropbox2global.h \
		lib/dropbox/qdropbox2account.h \
		lib/dropbox/qdropbox2entityinfo.h \
		lib/dropbox/qdropbox2file.h \
		lib/dropbox/qdropbox2entity.h \
		imageconverter.h \
		motiondetector.h \
		webstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o body.o body.cpp

bme280.o: bme280.cpp bme280.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bme280.o bme280.cpp

imageconverter.o: imageconverter.cpp imageconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageconverter.o imageconverter.cpp

filesender.o: filesender.cpp filesender.h \
		lib/dropbox/qdropbox2.h \
		lib/dropbox/qdropbox2common.h \
		lib/dropbox/qdropbox2global.h \
		lib/dropbox/qdropbox2account.h \
		lib/dropbox/qdropbox2entityinfo.h \
		lib/dropbox/qdropbox2file.h \
		lib/dropbox/qdropbox2entity.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filesender.o filesender.cpp

motiondetector.o: motiondetector.cpp motiondetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o motiondetector.o motiondetector.cpp

webstream.o: webstream.cpp webstream.h \
		camerathread.h \
		cameradev.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o webstream.o webstream.cpp

moc_qttelegrambot.o: moc_qttelegrambot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qttelegrambot.o moc_qttelegrambot.cpp

moc_networking.o: moc_networking.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networking.o moc_networking.cpp

moc_uartdevice.o: moc_uartdevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uartdevice.o moc_uartdevice.cpp

moc_modem.o: moc_modem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modem.o moc_modem.cpp

moc_dht.o: moc_dht.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dht.o moc_dht.cpp

moc_camerathread.o: moc_camerathread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camerathread.o moc_camerathread.cpp

moc_pininaction.o: moc_pininaction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pininaction.o moc_pininaction.cpp

moc_pinoutaction.o: moc_pinoutaction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pinoutaction.o moc_pinoutaction.cpp

moc_display.o: moc_display.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_display.o moc_display.cpp

moc_body.o: moc_body.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_body.o moc_body.cpp

moc_filesender.o: moc_filesender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filesender.o moc_filesender.cpp

moc_motiondetector.o: moc_motiondetector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_motiondetector.o moc_motiondetector.cpp

moc_webstream.o: moc_webstream.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_webstream.o moc_webstream.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/sbin || mkdir -p $(INSTALL_ROOT)/usr/sbin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/sbin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/sbin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/sbin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/sbin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

